### ISSUE TITLE
appHistory shows "undefined" values

### ISSUE THREAD

**Issue by gelolaus** [gelolaus/doon#1]
I can't seem to understand how I can configure appHistory.

My plan is that it should collect data from the appServiceFound and insert it in their right places:

**Replication:**
1. Go to the booking page and select any values you prefer.
2. Proceed to the next pages until you reach the Service Found page.
3. Wait for you to get back to the home page.
4. Open the History page.

**Expected result:**
On the unload event of the Service Found page it should save the data then send it to the History page once it's needed.

**Actual result:**
The values are undefined.
<img width="432" alt="Screenshot 2022-08-08 at 6 51 19 PM" src="https://user-images.githubusercontent.com/87759071/183401811-5a58c416-6aea-4017-8057-72270af080ec.png">

The code for **appHistory** can be found [by clicking here](https://github.com/gelolaus/doonWebApp/tree/main/appHistory). On the other hand, the code for **appServiceFound** can be found [by clicking here](https://github.com/gelolaus/doonWebApp/tree/main/appServiceFound).

Thank you in advanced for those who will be able to help me.

**Comment by rohanshankar** [comment]
If this is still an issue, I can try looking into it!

**Comment by 0xPranjl** [comment]
I have fixed the issue it was showing undefined due to handlesubmit function

**Comment by gelolaus** [comment]
Thank you!
